package com.satyam.mini_assignment.model;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "movie")
public class Movie {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBRangeKey
    private String imdb_title_id;
    @DynamoDBAttribute
    private String title;
    @DynamoDBAttribute
    private String original_title;
    @DynamoDBAttribute
    private String s_year;
    @DynamoDBAttribute
    private String date_published;
    @DynamoDBAttribute
    private String genre;
    @DynamoDBAttribute
    private int duration;
    @DynamoDBAttribute
    private String country;
    @DynamoDBAttribute
    private String language;
    @DynamoDBAttribute
    private String director;
    @DynamoDBAttribute
    private String writer;
    @DynamoDBAttribute
    private String production_company;
    @DynamoDBAttribute
    private String actors;
    @DynamoDBAttribute
    private String description;
    @DynamoDBAttribute
    private Double avg_vote;
    @DynamoDBAttribute
    private int votes;
    @DynamoDBAttribute
    private String budget;
    @DynamoDBAttribute
    private String usa_gross_income;
    @DynamoDBAttribute
    private String worlwide_gross_income;
    @DynamoDBAttribute
    private String metascore;
    @DynamoDBAttribute
    private int reviews_from_users;
    @DynamoDBAttribute
    private int reviews_from_critics;

}

